# The following redirect is intended for use with most SPAs that handle
# routing internally.


[[redirects]]
  from = "/api/data"
  to = "/.netlify/api/data"
  status = 200

  [redirects.headers]
     Access-Control-Allow-Origin = "..."